"""Add indexes to Company and TaxRecord tables

Revision ID: 42756377bc41
Revises: fd49dff01610
Create Date: 2024-12-13 00:29:59.988818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42756377bc41'
down_revision = 'fd49dff01610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)

    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tax_records_company_id'), ['company_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_records_company_id'))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.create_index('name', ['name'], unique=True)

    # ### end Alembic commands ###
